ChatCompletion(
    id='cfda0e79-5fce-4b40-82d1-852ba3e5379f',
    choices=
    [
        Choice
        (
        finish_reason='stop',
        index=0,
        logprobs=None,
        message=ChatCompletionMessage
            (
            content='你好！很高兴为您服务。有什么我可以帮助您的吗？',
            refusal=None, role='assistant',
            annotations=None, audio=None,
            function_call=None,
            tool_calls=None,
            reasoning_content='嗯，用户用中文说了“你好”，我应该用中文回应。先确认问候，然后问有什么可以帮忙的。要保持友好和自然。可能需要处理各种问题，比如翻译、信息查询等。准备好根据用户的后续问题调整回答。同时注意保持回答简洁明了，避免冗长。确保语法正确，用词恰当。如果有不确定的地方，应该礼貌地询问更多细节。总之，目标是提供有效的帮助，让用户满意。'
            )
        )
    ],
    created=1742461132,
    model='deepseek-reasoner',
    object='chat.completion',
    service_tier=None,
    system_fingerprint='fp_5417b77867_prod0225',
    usage=CompletionUsage
        (
        completion_tokens=105,
        prompt_tokens=12,
        total_tokens=117,
        completion_tokens_details=CompletionTokensDetails
            (
            accepted_prediction_tokens=None,
            audio_tokens=None,
            reasoning_tokens=91,
            rejected_prediction_tokens=None
            ),
        prompt_tokens_details=PromptTokensDetails
            (
            audio_tokens=None,
            cached_tokens=0
            ),
        prompt_cache_hit_tokens=0,
        prompt_cache_miss_tokens=12
        )
    )
